---
title: About the Quixotic Quant Blog
author: Aidan
date: '2017-08-29'
slug: opening-remarks
categories: []
tags: []
---


I think it’s worth a short post to explain where the name ‘Quixotic Quant’ came from, and why I’ve chosen it for this blog. The short version is that it’s a neat way of capturing a simple juxtaposition this blog seeks to embrace:
1. A high standard of rigour, objectivity, transparency to the quantitative analysis
2. A style that’s intellectually combative, provocative, and accessible and entertaining to a broad audience
Regarding the first objective, I’m convinced that the best standard for objectivity and rigour is to
publish not only a link to the data at source, but also the code-chunk that’s been used to conduct
the analysis. Anyone else can and should download R so that they can reproduce and verify, or
correct my work. Pushes are welcome on Github. My objective is to allow whatever objective
‘truth’ might be in the data to carry as much credibility as is possible, and hopefully transcend the
subjective value-judgements which (whilst essential for drawing policy conclusions from data) are
often polarising and distracting, particularly to a casual on-looker.
It should be noted that setting a very high or specific goal for a blog can be counterproductive to a
publication which in its origin was meant to be a web-based log of stream-of- consciousness type
thinking, abounding in ideas half-formed and imperfectly presented.
The second part of the juxtaposition is a deliberate way of managing this tension. I’ve recently
concluded that surest way of burying a great idea that’s well supported by the evidence is to try to
depersonalise it, and make it sound so objective and reasonable that it can’t be refuted. And, which
is worse, plenty of opposing ideas which are stupid and not even slightly supported by good analysis
have become ascendant only because colourful, opinionated people have been less bashful about
articulating their opinions succinctly. Good ideas won’t win any more by staying above the fray.
Consequently, posts on QQ will aim to use the as much code (hidden but accessible) as necessary,
and as few words as possible, to convey the strongest and clearest possible conclusions from the
analysis. Transparency, objectivity, and rigour will be prioritised in the numbers and graphs. The
prose will tend to economise on politeness and objectivity in order to drive harder and faster at
what may be concluded from the analysis.
This approach is partly informed by the Agile approach to software development, in particular the
Scrum method. Essentially the idea is that work is divided into short sprints to a fixed and
unchangeable goal, the output of which is something that works. It’s not a finished product, it
doesn’t have to be comprehensive, or perfectly documented, but it has to work. And at the end of
each sprint, all the stakeholders and developers meet to smash their heads together (scrum) to
evaluate what was produced, and figure out where to go in the next sprint. It’s quite a contrast to
traditional project management which seeks to describe as completely as possible what the final
product will do, and then keep the team sticking to the plan to deliver it. And, for software
development where new ideas, challenges, and opportunities emerge rapidly, it tends to work very
well.
Or in other words, whilst there are plenty of topics on which I feel I would like to write a book or
major article for a journal in order to fully articular my thesis, I’m going to try to share my thinking
argument by argument, and welcome the opportunity for the world to scrum with me on the way. If
my tone seems particularly strident, or my conclusions over-reached, please consider this by-

products of the intellectual aggression which I think is necessary to conclude each ‘sprint’. When
balancing the risks of over-shooting the mark, and meandering towards a vague objective, I will
deliberately favour the former. Please bear this in mind when making responses. I make absolutely
no warranty that the opinion expressed in one post will be maintained or defended in subsequent
posts, and welcome critical feedback.
The final characteristic of QQ posts is that I’ll tend to tilt most vigorously at ideas which probably
appear to have ‘windmill’ status. That is, they’re large static fixtures in our public intellectual
consciousness that seem so enduring, obvious, and innocuous that people have lost all willingness to
even challenge them, or examine their credibility. It’s these ideas, the enduring obsolete, which I
think are arguably far more damaging and dangerous than radical new ideas which seem bad and
reactionary.
Regarding post length, I’ll try to make sure that each blog post addresses at least (and generally at
most) one free-standing idea, and some data to support it. Each post won’t necessarily have all the
data that might support the idea, or address all the possible counter-arguments, or corollary
conclusions. But some working evidence to support an idea (or more often attempt to refute one)
will be the minimum for each post. Minor musings, or questions that don’t constitute such a post
I’ll try to keep to twitter.
Finally, the views expressed here are my own, and not that of any other organisation or company
that I might be associated with.